Repository echo-webkom/echo-web-frontend, pull requests merged in 2020-11, with the labels that each got.

#21 Responsive dummy-header
  .eslintignore
  .gitignore
  package.json
  src/assets/echo-logo-very-wide-logo-only.png
  src/assets/echo-logo-very-wide-text-only-white.png
  src/assets/echo-logo-very-wide-text-only.png
  src/assets/echo-logo-very-wide.png
  src/components/header.tsx
  src/components/layout.tsx
  src/components/navbar.tsx
  src/declarations.d.ts
  src/styles/globalTheme.js
  yarn.lock
Labels: enhancement

#25 Merge footer -> develop
  src/assets/echo.png
  src/assets/facebook.png
  src/assets/github.png
  src/assets/insta.png
  src/assets/twitter.png
  src/components/footer.tsx
  src/components/layout.tsx
Labels: enhancement

#24 ✨ basic event box
  src/assets/consulting.jpg
  src/components/event.tsx
  src/components/eventBox.tsx
  src/pages/index.tsx
Labels: enhancement

#27 :art: Improved code structure of header/navbar, some color mode things
  src/components/header.tsx
  src/components/layout.tsx
  src/components/navbar.tsx
  src/styles/globalTheme.js
Labels: enhancement

#28 Footer fix
  src/assets/consulting.jpg
  src/assets/echo.png
  src/assets/facebook.png
  src/assets/github.png
  src/assets/insta.png
  src/assets/twitter.png
  src/components/event.tsx
  src/components/eventBox.tsx
  src/components/footer.tsx
  src/components/header.tsx
  src/components/layout.tsx
  src/components/navbar.tsx
  src/pages/index.tsx
  src/styles/globalTheme.js
Labels: enhancement

#29 Merge Feature/footer -> develop
  src/assets/echo-logo-very-wide-text-only.png
  src/assets/echo.png
  src/assets/facebook.png
  src/assets/github.png
  src/assets/insta.png
  src/assets/twitter.png
  src/components/footer.tsx
Labels: enhancement

#30 Feature/page query -> develop
  gatsby-browser.js
  gatsby-config.js
  gatsby-node.js
  gatsby-ssr.js
  package.json
  src/gatsby-plugin-chakra-ui/theme.js
  src/markdown.js
  src/templates/blogPost.tsx
  yarn.lock
Labels: enhancement

#31 Feature/footer -> develop
  src/components/footer.tsx
  src/components/layout.tsx
  src/gatsby-plugin-chakra-ui/theme.js
Labels: enhancement

#32 :arrow_up: Upgraded to chakraui 1.0.0
  gatsby-config.js
  gatsby-ssr.js
  package.json
  src/components/event.tsx
  src/components/eventBox.tsx
  src/components/footer.tsx
  src/components/header.tsx
  src/components/layout.tsx
  src/components/navbar.tsx
  src/gatsby-plugin-chakra-ui/theme.js
  src/markdown.js
  src/templates/blogPost.tsx
  yarn.lock
Labels: enhancement

#33 :ambulance: Fixed theme bug after chakra release
  gatsby-ssr.js
  src/@chakra-ui/gatsby-plugin/theme.js
Labels: bug

#39 Test/environment
  .babelrc
  jest.config.js
  jest.setup.js
  package.json
  src/components/__tests__/events.test.tsx
  src/components/__tests__/footer.test.tsx
  src/components/__tests__/header.test.tsx
  src/components/__tests__/layout.test.tsx
  src/components/__tests__/navbar.test.tsx
  src/components/__tests__/testing-utils.js
  src/components/__tests__/testing-wrapper.tsx
  src/components/events.tsx
  src/components/footer.tsx
  src/components/header.tsx
  src/components/layout.tsx
  src/components/navbar.tsx
  yarn.lock
Labels: Testing, dependencies
