Repository echo-webkom/echo-web-frontend, pull requests merged in 2021-05, with the labels that each got.

#270 🔖 Added notes to automatic release tag workflow
  .github/workflows/release_tag.yaml
Labels: devops :rocket:

#273 ✅ Add tests for event-block and post-block
  .husky/pre-commit
  src/components/__tests__/event-block.test.tsx
  src/components/__tests__/post-block.test.tsx
  src/components/bedpres-block.tsx
  src/components/bedpres-preview.tsx
  src/components/event-block.tsx
  src/components/event-preview.tsx
  src/components/member-profile.tsx
  src/components/post-block.tsx
  src/components/post-list.tsx
  src/components/post-preview.tsx
  src/pages/bedpres/index.tsx
  src/pages/events/index.tsx
  src/pages/index.tsx
  src/pages/posts/index.tsx
Labels: bug :bug:, testing :test_tube:

#275 🐛 Fix bug where posts show up on multiple pages
  src/components/post-list.tsx
  src/pages/posts/index.tsx
Labels: bug :bug:

#278 Create LICENSE
  LICENSE
Labels: manual work :muscle:

#279 Several fixes
  package.json
  src/components/bedpres-block.tsx
  src/components/bedpres-preview.tsx
  src/components/header.tsx
  src/components/layout.tsx
  src/components/post-list.tsx
  src/components/post-preview.tsx
  src/markdown.js
  src/pages/bedpres/[slug].tsx
  src/pages/events/[slug].tsx
  src/pages/index.tsx
  src/pages/posts/[slug].tsx
  yarn.lock
Labels: bug :bug:, refactoring :recycle:

#281 🐛 Fixed countdown bug
  src/components/countdown.tsx
  src/components/header.tsx
  src/components/navbar.tsx
  src/pages/bedpres/[slug].tsx
Labels: bug :bug:

#282 📱 Fixed upcoming bedpres not on top
  src/pages/bedpres/index.tsx
  src/pages/events/index.tsx
Labels: user interface :lipstick:

#285 Refactor entry lists
  src/components/__tests__/bedpres-block.test.tsx
  src/components/__tests__/event-block.test.tsx
  src/components/bedpres-block.tsx
  src/components/entry-box.tsx
  src/components/entry-list.tsx
  src/components/entry-overview.tsx
  src/components/event-block.tsx
  src/components/hsp.tsx
  src/lib/generateRssFeed.ts
  src/pages/bedpres/index.tsx
  src/pages/events/index.tsx
  src/pages/index.tsx
Labels: architecture :classical_building:, manual work :muscle:, refactoring :recycle:

#288 🎨 Add waitlist and refactor responses
  src/components/bedpres-form.tsx
  src/components/bedpres-view.tsx
  src/lib/api/registration.ts
  src/pages/bedpres/[slug].tsx
Labels: feature :sparkles:, refactoring :recycle:

#289 ✨ Bedpres spots counter
  src/components/bedpres-form.tsx
  src/components/bedpres-view.tsx
  src/pages/bedpres/[slug].tsx
Labels: feature :sparkles:, user interface :lipstick:

#294 Fixed the unused vars problem
  .eslintrc.js
  src/components/post-list.tsx
  src/pages/events/[slug].tsx
Labels: bug :bug:, devops :rocket:

#313 ✨ Add optional questions on bedpres form
  src/components/bedpres-form.tsx
  src/lib/api/__tests__/bedpres.test.ts
  src/lib/api/__tests__/mock-responses.ts
  src/lib/api/bedpres.ts
  src/lib/api/schema.ts
  src/pages/bedpres/[slug].tsx
Labels: feature :sparkles:, user interface :lipstick:

#325 ✨ Add bedpres answers
  .dockerignore
  .github/workflows/cypress_test.yaml
  .gitignore
  Dockerfile
  cypress/fixtures/bedpres.json
  cypress/fixtures/example.json
  cypress/fixtures/users.json
  cypress/integration/bedpres-registration.spec.ts
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  cypress/tsconfig.json
  docker-compose.yaml
  src/components/bedpres-form.tsx
  src/components/bedpres-view.tsx
  src/lib/api/__tests__/mock-responses.ts
  src/lib/api/bedpres.ts
  src/lib/api/registration.ts
  src/pages/bedpres/[slug].tsx
Labels: feature :sparkles:

#350 ➖ Remove identity-obj-proxy
  package.json
  yarn.lock
Labels: dependencies :handshake:

#351 Update header.tsx
  src/components/header.tsx
Labels: feature :sparkles:
