Repository echo-webkom/echo-web-frontend, pull requests merged in 2021-04, with the labels that each got.

#187 ➖ Removed unused and direct dependencies
  package.json
  yarn.lock
Labels: dependencies :handshake:

#198 ♻️ Fixed SEO, markdown typos and README
  README.md
  public/static/for-bedrifter/bedriftspresentasjon.md
  public/static/for-bedrifter/stillingsutlysninger.md
  public/static/for-studenter/undergrupper.md
  public/static/for-studenter/underorganisasjoner.md
  public/static/om-oss/hvem-er-vi.md
  src/components/seo.tsx
  src/components/static-info.tsx
  src/config.js
  src/markdown.js
  src/pages/index.tsx
Labels: documentation :memo:, refactoring :recycle:

#211 hotfix/event spots
  package.json
  public/static/for-studenter/undergrupper.md
  src/lib/api/event.ts
  src/pages/events/[slug].tsx
  yarn.lock
Labels: bug :bug:, dependencies :handshake:

#216 Removed raw-loader as it is deprecated
  next.config.js
  package.json
  yarn.lock
Labels: refactoring :recycle:

#217 🚀 Added automated weekly release
  .github/workflows/create_pr.yaml
  .github/workflows/release_tag.yaml
  .github/workflows/test.yaml
Labels: devops :rocket:

#218 Manual weekly release
  .github/workflows/create_pr.yaml
  .github/workflows/release_tag.yaml
  .github/workflows/test.yaml
  next.config.js
  package.json
  yarn.lock
Labels: devops :rocket:, release :label:

#220 📝 Fixed links on masterinfo
  public/static/for-studenter/masterinfo.md
Labels: bug :bug:

#229 Feature/typesafe api
  package.json
  src/components/__tests__/bedpres-block.test.tsx
  src/components/bedpres-block.tsx
  src/components/bedpres-preview.tsx
  src/components/events-block.tsx
  src/components/member-profile.tsx
  src/components/post-list.tsx
  src/components/post-preview.tsx
  src/components/student-group-section.tsx
  src/components/student-group-view.tsx
  src/lib/api/__tests__/bedpres.test.ts
  src/lib/api/__tests__/event.test.ts
  src/lib/api/__tests__/minute.test.ts
  src/lib/api/__tests__/mock-responses.ts
  src/lib/api/__tests__/post.test.ts
  src/lib/api/__tests__/student-group.test.ts
  src/lib/api/bedpres.ts
  src/lib/api/decoders.ts
  src/lib/api/event.ts
  src/lib/api/index.ts
  src/lib/api/minute.ts
  src/lib/api/post.ts
  src/lib/api/schema.ts
  src/lib/api/student-group.ts
  src/lib/types/author.ts
  src/lib/types/bedpres.ts
  src/lib/types/event.ts
  src/lib/types/index.ts
  src/lib/types/minute.ts
  src/lib/types/post.ts
  src/lib/types/student-group.ts
  src/pages/bedpres/[slug].tsx
  src/pages/bedpres/index.tsx
  src/pages/events/[slug].tsx
  src/pages/for-studenter.tsx
  src/pages/index.tsx
  src/pages/om-oss.tsx
  src/pages/posts/[slug].tsx
  src/pages/posts/index.tsx
  yarn.lock
Labels: architecture :classical_building:, refactoring :recycle:, testing :test_tube:

#230 📝 Fixed link on /for-bedrifter
  public/static/for-bedrifter/stillingsutlysninger.md
Labels: bug :bug:

#232 ✅ Add tests for static-info and student-group-section
  jest.setup.js
  src/components/__tests__/header.test.tsx
  src/components/__tests__/layout.test.tsx
  src/components/__tests__/static-info.test.tsx
  src/components/__tests__/student-group-section.test.tsx
  src/components/static-info.tsx
  src/components/student-group-section.tsx
Labels: testing :test_tube:

#237 Fixed avatar initials
  src/components/member-profile.tsx
Labels: bug :bug:

#239 useTimeout hook, better bedpres logic
  src/lib/hooks/index.ts
  src/lib/hooks/use-timeout.tsx
  src/pages/bedpres/[slug].tsx
Labels: architecture :classical_building:

#242 :white_check_mark: Updating test according to component
  src/components/__tests__/bedpres-block.test.tsx
Labels: testing :test_tube:

#241 Readme issues and template fixes
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feedback.md
  .github/workflows/test.yaml
  README.md
Labels: documentation :memo:, feedback :scroll:, manual work :muscle:

#243 :ambulance: Quick template fix
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: feedback :scroll:

#246 Error handling
  src/components/bedpres-block.tsx
  src/components/error-box.tsx
  src/components/events-block.tsx
  src/components/post-list.tsx
  src/components/student-group-section.tsx
  src/lib/api/bedpres.ts
  src/lib/api/errors.ts
  src/lib/api/event.ts
  src/lib/api/minute.ts
  src/lib/api/post.ts
  src/lib/api/student-group.ts
  src/pages/bedpres/[slug].tsx
  src/pages/bedpres/index.tsx
  src/pages/events/[slug].tsx
  src/pages/for-studenter.tsx
  src/pages/index.tsx
  src/pages/om-oss.tsx
  src/pages/posts/[slug].tsx
Labels: feature :sparkles:, manual work :muscle:, refactoring :recycle:

#247 Better Progressbar
  package.json
  src/pages/_app.tsx
  yarn.lock
Labels: feature :sparkles:, refactoring :recycle:

#250 Fix/package json cleanup
  package.json
  yarn.lock
Labels: dependencies :handshake:, manual work :muscle:

#254 💄 Swap "Kommende" and "Tidligere" on /bedpres
  src/pages/bedpres/index.tsx
Labels: user interface :lipstick:

#259 Events page
  src/components/bedpres-block.tsx
  src/components/event-preview.tsx
  src/components/events-block.tsx
  src/components/post-block.tsx
  src/lib/api/event.ts
  src/lib/api/schema.ts
  src/pages/bedpres/index.tsx
  src/pages/events/index.tsx
  src/pages/index.tsx
Labels: feature :sparkles:, refactoring :recycle:

#260 Fix post card
  src/components/events-block.tsx
  src/components/post-block.tsx
  src/components/post-card.tsx
  src/pages/events/index.tsx
Labels: refactoring :recycle:, user interface :lipstick:

#264 Implemented rss
  .gitignore
  src/lib/generateRssFeed.tsx
  src/pages/index.tsx
Labels: feature :sparkles:

#268 🐛 Fixed rss only routing posts
  src/lib/generateRssFeed.tsx
Labels: bug :bug:
