Repository echo-webkom/echo-web-frontend, pull requests merged in 2021-11, with the labels that each got.

#698 🔧 Make next lint work with lint-staged
  .lintstagedrc.js
  package.json
Labels: architecture :classical_building:

#700 ➖ Remove prop-types
  package.json
  src/components/__tests__/testing-wrapper.tsx
  src/components/layout.tsx
  yarn.lock
Labels: pls help :question:, dependencies :handshake:

#701 🚀 Add lint & format action and yaml format
  .github/workflows/cypress_test.yaml
  .github/workflows/jest_test.yaml
  .github/workflows/lint_format.yaml
  .lintstagedrc.js
  docker-compose.ci.yaml
  docker-compose.yaml
  package.json
Labels: devops :rocket:

#703 🏷️ JavaScript -> TypeScript
  src/markdown.ts
  src/styles/themes/halloween-theme.ts
  src/styles/themes/main-theme.ts
Labels: refactoring :recycle:

#704 🚸 Easier to understand UI
  src/components/happening-meta-info.tsx
  src/components/happening.tsx
Labels: user interface :lipstick:

#708 🔧 Fix 'no-console' only producing a warning
  package.json
Labels: bug :bug:

#705 🚀 Add action for auto-rebasing pull request
  .github/workflows/rebase.yaml
Labels: devops :rocket:

#713 🐛 Fix broken workflow
  .github/workflows/rebase.yaml
Labels: bug :bug:

#711 ♻️ Add lint errors for imports/exports
  package.json
  src/components/__tests__/testing-utils.js
  src/components/happening-meta-info.tsx
  src/components/header.tsx
  src/components/minute-list.tsx
  src/components/registration-form.tsx
  src/lib/api/api.ts
  src/lib/api/happening.ts
  src/lib/api/index.ts
  src/lib/api/minute.ts
  src/lib/api/post.ts
  src/lib/api/registration.ts
  src/lib/api/student-group.ts
  src/pages/bedpres/[slug].tsx
  src/pages/events/[slug].tsx
  src/pages/index.tsx
  src/pages/om-oss.tsx
  src/pages/posts/[slug].tsx
Labels: dependencies :handshake:, architecture :classical_building:

#725 💄 Update post meta info
  src/pages/posts/[slug].tsx
Labels: user interface :lipstick:

#726 🐛 Fixed footer margin
  src/components/layout.tsx
Labels: bug :bug:, user interface :lipstick:

#731 💄 Fix misaligned boxes
  src/components/hsp.tsx
Labels: user interface :lipstick:

#732 Feature/header msgs
  src/components/header.tsx
Labels: user interface :lipstick:, refactoring :recycle:

#734 🎨 Add more eslint rules
  package.json
  src/components/happening.tsx
  src/lib/api/happening.ts
Labels: architecture :classical_building:

#737 Feature/feedback in footer
  src/components/footer.tsx
Labels: user interface :lipstick:

#751 ✨ Spot ranges with infinite spots
  src/components/happening-meta-info.tsx
Labels: feature :sparkles:, user interface :lipstick:

#752 🐛 Fix spotsText not returning
  src/components/happening-meta-info.tsx
Labels: bug :bug:

#753 🐛 Fix spotsText ternary
  src/components/happening-meta-info.tsx
Labels: bug :bug:

#754 🐛 Fix showing 0 registrations for infinite spots
  src/components/happening-meta-info.tsx
Labels: bug :bug:

#757 ✅ Add tests for happening-meta-info
  src/components/__tests__/happening-meta-info.test.tsx
  src/components/happening-meta-info.tsx
Labels: testing :test_tube:
