Repository echo-webkom/echo-web-frontend, pull requests merged in 2021-02, with the labels that each got.

#51 :arrow_up: Upgraded dependencies
  package.json
  yarn.lock
Labels: dependencies :handshake:

#52 feature/api -> develop
  package.json
  src/components/__tests__/navbar.test.tsx
  src/lib/api/api.ts
  src/lib/api/event.ts
  src/lib/api/post.ts
  src/pages/events/[slug].tsx
  src/pages/posts/[slug].tsx
  yarn.lock
Labels: feature :sparkles:

#56 Feature/api
  src/lib/api/__mocks__/event.ts
  src/lib/api/__mocks__/post.ts
  src/lib/api/__mocks__/queries.ts
  src/lib/api/__tests__/event.test.tsx
  src/lib/api/__tests__/post.test.tsx
  tsconfig.json
Labels: testing :test_tube:

#57 Support for static markdown files
  next.config.js
  package.json
  src/declarations.d.ts
  yarn.lock
Labels: feature :sparkles:

#59 Updated API, implemented testing framework for API
  jest.config.js
  package.json
  src/lib/api/__mocks__/event.ts
  src/lib/api/__mocks__/post.ts
  src/lib/api/__tests__/event.test.ts
  src/lib/api/__tests__/event.test.tsx
  src/lib/api/__tests__/mock-responses.ts
  src/lib/api/__tests__/post.test.ts
  src/lib/api/__tests__/post.test.tsx
  src/lib/api/event.ts
  src/lib/api/index.ts
  src/lib/api/post.ts
  src/lib/api/schema.ts
  src/lib/index.ts
  src/lib/types/index.ts
  src/pages/events/[slug].tsx
  src/pages/posts/[slug].tsx
  yarn.lock
Labels: architecture :classical_building:, dependencies :handshake:, documentation :memo:, testing :test_tube:
