Repository echo-webkom/echo-web-frontend, pull requests merged in 2021-08, with the labels that each got.

#445 📝 Update masterinfo.md
  public/static/for-studenter/masterinfo.md
Labels: documentation :memo:

#410 ➖ Remove unused dependencies
  package.json
  src/lib/api/__tests__/bedpres.test.ts
  src/lib/api/__tests__/event.test.ts
  src/lib/api/__tests__/minute.test.ts
  src/lib/api/__tests__/post.test.ts
  src/lib/api/__tests__/student-group.test.ts
  yarn.lock
Labels: dependencies :handshake:, refactoring :recycle:

#384 🔧 Move config files to package.json
  .eslintrc.json
  jest.config.js
  package.json
  renovate.json
Labels: refactoring :recycle:

#479 💬 Add forms for financial support and feedback
  next-env.d.ts
  public/static/for-studenter/okonomiskStotte.md
  public/static/for-studenter/tilbakemeldingsskjema.md
  src/pages/for-studenter.tsx
Labels: feature :sparkles:

#477 Hotfix/header text
  src/components/header.tsx
Labels: user interface :lipstick:

#480 🚨 Fix lint errors on tests
  src/components/__tests__/post-block.test.tsx
  src/lib/api/__tests__/bedpres.test.ts
  src/lib/api/__tests__/event.test.ts
  src/lib/api/__tests__/minute.test.ts
  src/lib/api/__tests__/post.test.ts
  src/lib/api/__tests__/student-group.test.ts
  tsconfig.json
Labels: bug :bug:, testing :test_tube:

#483 ♻️ Refactor workflows
  .github/workflows/create_pr.yaml
  .github/workflows/cypress_test_dev.yaml
  .github/workflows/cypress_test_prod.yaml
  .github/workflows/jest_test.yaml
  .github/workflows/release_tag.yaml
  Dockerfile
  README.md
  docker-compose.yaml
  package.json
  yarn.lock
Labels: refactoring :recycle:

#484 🐛 Fixed a bedpres registration bug
  src/components/countdown.tsx
  src/pages/bedpres/[slug].tsx
Labels: bug :bug:

#486 fix/tba spots
  src/pages/bedpres/[slug].tsx
Labels: user interface :lipstick:

#487 🐛 Fixed rss notification bug
  src/lib/generate-rss-feed.ts
Labels: bug :bug:

#489 Add restriction on degree year on bedpres registration
  .dockerignore
  .env.example
  .gitignore
  Dockerfile
  docker-compose.yaml
  src/components/bedpres-form.tsx
  src/components/countdown.tsx
  src/lib/api/__tests__/bedpres.test.ts
  src/lib/api/__tests__/mock-responses.ts
  src/lib/api/bedpres.ts
  src/lib/api/schema.ts
  src/pages/bedpres/[slug].tsx
Labels: feature :sparkles:

#494 ✨ Registration and waitlist count in UI
  src/lib/api/registration.ts
  src/pages/bedpres/[slug].tsx
Labels: feature :sparkles:, refactoring :recycle:

#499 Registration count (master)
  .dockerignore
  Dockerfile
  package.json
  src/lib/api/registration.ts
  src/pages/bedpres/[slug].tsx
  yarn.lock
Labels: feature :sparkles:

#504 Feature/happening refactor registation
  cypress/fixtures/event.json
  cypress/integration/event-registration.spec.ts
  docker-compose.yaml
  src/components/bedpres-view.tsx
  src/components/countdown.tsx
  src/components/happening-form.tsx
  src/components/happening.tsx
  src/lib/api/__tests__/event.test.ts
  src/lib/api/__tests__/mock-responses.ts
  src/lib/api/bedpres.ts
  src/lib/api/decoders.ts
  src/lib/api/event.ts
  src/lib/api/registration.ts
  src/lib/api/schema.ts
  src/pages/bedpres/[slug].tsx
  src/pages/events/[slug].tsx
Labels: feature :sparkles:, testing :test_tube:, refactoring :recycle:

#506 🚑 Fixed markdown links not breaking
  src/components/happening.tsx
Labels: bug :bug:, user interface :lipstick:

#507 🚑 Fixed markdown links not breaking
  src/components/happening.tsx
Labels: bug :bug:, user interface :lipstick:

#509 🚑 Fix spots counter
  src/components/happening.tsx
Labels: bug :bug:

#511 hotfix/countdown server side
  src/components/countdown.tsx
  src/components/happening.tsx
  src/pages/bedpres/[slug].tsx
  src/pages/events/[slug].tsx
Labels: bug :bug:

#512 Hotfix to develop
  src/components/countdown.tsx
  src/components/happening.tsx
  src/pages/bedpres/[slug].tsx
  src/pages/events/[slug].tsx
Labels: bug :bug:

#513 🚑 Fixed overflow in useTimeout
  src/pages/bedpres/[slug].tsx
  src/pages/events/[slug].tsx
Labels: bug :bug:

#514 hotfix -> develop
  src/pages/bedpres/[slug].tsx
  src/pages/events/[slug].tsx
Labels: bug :bug:
