Repository echo-webkom/echo-web-frontend, pull requests merged in 2021-10, with the labels that each got.

#589 🐛 Fix year showing unnecessarily on happening
  src/components/happening-meta-info.tsx
Labels: bug :bug:

#596 ♻️ Refactor registration form
  src/components/form-question.tsx
  src/components/form-term.tsx
  src/components/registration-form.tsx
Labels: refactoring :recycle:

#689 💄 Cooler colormode button :sunglasses:
  src/components/color-mode-button.tsx
  src/components/navbar.tsx
Labels: user interface :lipstick:

#696 🎨 Fix unused var and add error in eslint
  package.json
  src/components/navbar.tsx
Labels: bug :bug:
