Repository echo-webkom/echo-web-frontend, pull requests merged in 2021-09, with the labels that each got.

#515 🚑 Change header text
  src/components/header.tsx
Labels: documentation :memo:

#516 Hotfix/header text (develop)
  src/components/header.tsx
Labels: documentation :memo:

#526 🐛 Fix degree year text when min & max year is same
  src/components/happening.tsx
Labels: bug :bug:, user interface :lipstick:

#528 ✨ Add utleggssskjema
  public/static/for-studenter/anonymeTilbakemeldinger.md
  public/static/for-studenter/utleggsskjema.md
  src/pages/for-studenter.tsx
Labels: feature :sparkles:

#532 🐛 Fix broken link
  public/static/for-studenter/utleggsskjema.md
Labels: bug :bug:

#538 💚 Add cache to workflows for faster CI
  .dockerignore
  .github/workflows/cypress_test_dev.yaml
  .github/workflows/cypress_test_prod.yaml
  .github/workflows/jest_test.yaml
  docker-compose.ci.yaml
Labels: devops :rocket:, refactoring :recycle:

#545 Refaktorering
  src/components/__tests__/footer.test.tsx
  src/components/__tests__/header.test.tsx
  src/components/__tests__/layout.test.tsx
  src/components/__tests__/navbar.test.tsx
  src/components/__tests__/static-info.test.tsx
  src/components/__tests__/student-group-section.test.tsx
  src/components/__tests__/testing-utils.js
  src/components/__tests__/testing-wrapper.tsx
  src/components/article.tsx
  src/components/bedpres-preview.tsx
  src/components/bedpres-view.tsx
  src/components/button-link.tsx
  src/components/countdown.tsx
  src/components/entry-box.tsx
  src/components/error-box.tsx
  src/components/footer.tsx
  src/components/happening-meta-info.tsx
  src/components/happening.tsx
  src/components/header.tsx
  src/components/hsp.tsx
  src/components/icon-text.tsx
  src/components/layout.tsx
  src/components/navbar.tsx
  src/components/post-block.tsx
  src/components/post-list.tsx
  src/components/post-preview.tsx
  src/components/registration-form.tsx
  src/components/section.tsx
  src/components/seo.tsx
  src/components/static-info.tsx
  src/components/student-group-section.tsx
  src/lib/api/__tests__/bedpres.test.ts
  src/lib/api/__tests__/event.test.ts
  src/lib/api/__tests__/minute.test.ts
  src/lib/api/__tests__/post.test.ts
  src/lib/api/__tests__/student-group.test.ts
  src/lib/api/bedpres.ts
  src/lib/api/event.ts
  src/lib/api/minute.ts
  src/lib/api/post.ts
  src/lib/api/registration.ts
  src/lib/api/student-group.ts
  src/lib/hooks/index.ts
  src/lib/hooks/use-countdown.ts
  src/markdown.js
  src/pages/404.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/bedpres/[slug].tsx
  src/pages/bedpres/index.tsx
  src/pages/events/[slug].tsx
  src/pages/events/index.tsx
  src/pages/for-bedrifter.tsx
  src/pages/for-studenter.tsx
  src/pages/index.tsx
  src/pages/om-oss.tsx
  src/pages/posts/[slug].tsx
  src/pages/posts/index.tsx
  src/styles/fonts.tsx
Labels: refactoring :recycle:

#551 🐛 Fixed a bug where total spots doesn't show up before registration opens
  src/components/happening-meta-info.tsx
Labels: bug :bug:

#560 ✨ Add more header messages
  src/components/header.tsx
Labels: feature :sparkles:, user interface :lipstick:

#562 🚀 Add workflow for editing PR
  .github/workflows/edit_pr.yaml
Labels: devops :rocket:

#573 ♻️ Combine BEDKOM_KEY and WEBKOM_KEY to single env
  .env.example
  .github/workflows/cypress_test_dev.yaml
  .github/workflows/cypress_test_prod.yaml
  docker-compose.ci.yaml
  docker-compose.yaml
  src/lib/api/registration.ts
  src/pages/bedpres/[slug].tsx
  src/pages/events/[slug].tsx
Labels: refactoring :recycle:

#578 ✨ Add ability to restrict spots to degree year
  src/components/happening-meta-info.tsx
  src/components/happening.tsx
  src/lib/api/registration.ts
  src/pages/bedpres/[slug].tsx
  src/pages/events/[slug].tsx
Labels: feature :sparkles:, user interface :lipstick:

#567 🐛 Fix workflow triggering on unmerged closed PR's
  .github/workflows/release_tag.yaml
Labels: bug :bug:

#582 ✏️ Add link to Bedkom FAQ in registration form
  src/components/registration-form.tsx
Labels: user interface :lipstick:

#581 🐛 Fix conditionals on happening meta info text
  src/components/happening-meta-info.tsx
  src/components/happening.tsx
Labels: bug :bug:

#584 🐛 Fix degree year not showing on split registration
  src/components/happening-meta-info.tsx
Labels: bug :bug:
