Repository echo-webkom/echo-web-frontend, pull requests merged in 2021-03, with the labels that each got.

#65 Feature/post collection
  src/components/post-list.tsx
  src/components/post-preview.tsx
  src/pages/posts/index.tsx
Labels: feature :sparkles:

#66 Feature/events block
  package.json
  src/components/__tests__/events.test.tsx
  src/components/event-block.tsx
  src/components/events.tsx
  src/pages/index.tsx
  yarn.lock
Labels: feature :sparkles:, testing :test_tube:

#62 Bedpres page, content type and data fetching
  src/lib/api/__tests__/bedpres.test.ts
  src/lib/api/__tests__/mock-responses.ts
  src/lib/api/bedpres.ts
  src/lib/api/index.ts
  src/lib/api/schema.ts
  src/lib/types/bedpres.ts
  src/lib/types/index.ts
  src/pages/bedpres/[slug].tsx
Labels: architecture :classical_building:, feature :sparkles:, testing :test_tube:

#70 Styling and bedpres -> develop
  public/bekk.png
  public/echo-logo-black.svg
  public/echo-logo-very-wide-white.png
  public/echo-logo-white.svg
  public/static/for-studenter/undergrupper.md
  src/components/__tests__/bedpres-block.test.tsx
  src/components/__tests__/events.test.tsx
  src/components/__tests__/footer.test.tsx
  src/components/__tests__/header.test.tsx
  src/components/bedpres-block.tsx
  src/components/content-box.tsx
  src/components/event-block.tsx
  src/components/footer.tsx
  src/components/header.tsx
  src/components/layout.tsx
  src/components/navbar.tsx
  src/components/post-block.tsx
  src/lib/api/__tests__/bedpres.test.ts
  src/lib/api/__tests__/event.test.ts
  src/lib/api/__tests__/post.test.ts
  src/lib/api/api.ts
  src/lib/api/event.ts
  src/pages/_document.tsx
  src/pages/bedpres/[slug].tsx
  src/pages/events/[slug].tsx
  src/pages/index.tsx
  src/pages/posts/[slug].tsx
  src/styles/theme.js
Labels: devops :rocket:

#84 Bedpres sorting by upcoming
  src/lib/api/schema.ts
Labels: feature :sparkles:

#85 Fixed bug in bedpres-block
  src/lib/api/bedpres.ts
  src/lib/api/schema.ts
Labels: bug :bug:

#87 Testing/components
  src/components/__tests__/bedpres-block.test.tsx
  src/components/__tests__/header.test.tsx
  src/components/__tests__/navbar.test.tsx
  src/components/__tests__/post-block.test.tsx
  src/components/bedpres-block.tsx
  src/components/content-box.tsx
  src/components/header.tsx
  src/components/navbar.tsx
  src/components/post-block.tsx
Labels: testing :test_tube:

#92 🔧 Temp removal of PR hourly limit for Renovate bot
  renovate.json
Labels: devops :rocket:

#118 Feature/post block images
  src/components/__tests__/bedpres-block.test.tsx
  src/components/post-block.tsx
  src/lib/api/__tests__/mock-responses.ts
  src/lib/api/__tests__/post.test.ts
  src/lib/api/post.ts
  src/lib/api/schema.ts
  src/lib/types/post.ts
  src/pages/posts/[slug].tsx
Labels: feature :sparkles:

#124 Timeout integer overflow fix
  src/pages/bedpres/[slug].tsx
Labels: bug :bug:

#131 Husky, eslint, timeout
  .eslintrc.js
  .husky/.gitignore
  .husky/pre-commit
  package.json
  src/components/__tests__/bedpres-block.test.tsx
  src/components/__tests__/post-block.test.tsx
  src/pages/bedpres/[slug].tsx
Labels: bug :bug:, dependencies :handshake:

#136 Fixed timeout-bug
  src/pages/bedpres/[slug].tsx
Labels: bug :bug:

#138 🔧 Added stabilityDays to Renovate Bot config
  renovate.json
Labels: devops :rocket:

#143 🔧 Made Renovate Bot not create PR before stable
  renovate.json
Labels: devops :rocket:

#144 Workshop changes -> develop
  public/static/for-studenter/masterinfo.md
  public/static/for-studenter/underorganisasjoner.md
  src/components/__tests__/footer.test.tsx
  src/components/__tests__/post-block.test.tsx
  src/components/bedpres-block.tsx
  src/components/content-box.tsx
  src/components/events-block.tsx
  src/components/footer.tsx
  src/components/header.tsx
  src/components/layout.tsx
  src/components/navbar.tsx
  src/components/post-block.tsx
  src/components/post-list.tsx
  src/components/post-preview.tsx
  src/lib/api/event.ts
  src/lib/api/schema.ts
  src/pages/_app.tsx
  src/pages/bedpres/[slug].tsx
  src/pages/events/[slug].tsx
  src/pages/index.tsx
  src/styles/fonts.tsx
  src/styles/theme.js
Labels: feature :sparkles:, user interface :lipstick:

#145 Meeting minutes
  public/static/om-oss/hvem-er-vi.md
  src/lib/api/index.ts
  src/lib/api/minute.ts
  src/lib/api/schema.ts
  src/lib/types/index.ts
  src/lib/types/minute.ts
  src/pages/for-bedrifter.tsx
  src/pages/for-studenter.tsx
  src/pages/om-oss.tsx
Labels: feature :sparkles:, user interface :lipstick:

#147 Added public HSP contract
  public/static/om-oss/bekk.md
  src/pages/om-oss.tsx
Labels: feature :sparkles:, manual work :muscle:

#146 :heavy_minus_sign: Migrated from Moment.js to date-fns
  package.json
  src/lib/api/bedpres.ts
  src/pages/bedpres/[slug].tsx
  src/pages/events/[slug].tsx
  src/pages/posts/[slug].tsx
  yarn.lock
Labels: dependencies :handshake:

#151 Updated chakra-ui and framer motion
  package.json
  yarn.lock
Labels: dependencies :handshake:

#152 Bedpres collection page
  package.json
  src/components/bedpres-block.tsx
  src/components/bedpres-preview.tsx
  src/pages/bedpres/index.tsx
  src/pages/index.tsx
Labels: feature :sparkles:

#153 Added progress bar
  package.json
  src/components/events-block.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
  yarn.lock
Labels: feature :sparkles:, user interface :lipstick:

#155 Fixed a padding issue in posts
  src/pages/posts/[slug].tsx
Labels: user interface :lipstick:

#157 Update version
  package.json
Labels: devops :rocket:

#160 Hotfix bedpres query, post content model
  src/components/bedpres-block.tsx
  src/lib/api/bedpres.ts
  src/lib/api/schema.ts
  src/pages/index.tsx
Labels: bug :bug:, user interface :lipstick:

#159 Fixed bedpres query, and posts content model
  src/components/bedpres-block.tsx
  src/lib/api/bedpres.ts
  src/lib/api/schema.ts
  src/pages/index.tsx
Labels: bug :bug:, user interface :lipstick:

#161 Fixed bedpres error message
  src/components/bedpres-block.tsx
Labels: bug :bug:

#162 Hotfix error message
  src/components/bedpres-block.tsx
Labels: bug :bug:

#163 :ambulance: Fixed index only fetching 3 bedpreses
  src/components/bedpres-block.tsx
  src/pages/index.tsx
Labels: bug :bug:

#164 Hotfix/bedpres filter fix
  src/components/bedpres-block.tsx
  src/pages/index.tsx
Labels: bug :bug:

#165 Better bepres sidebar styling
  src/pages/bedpres/[slug].tsx
Labels: user interface :lipstick:

#166 :recycle: Fixed chakra icons
  src/components/events-block.tsx
  src/components/header.tsx
  src/components/navbar.tsx
  src/components/post-preview.tsx
  src/pages/bedpres/[slug].tsx
  src/pages/events/[slug].tsx
  src/pages/om-oss.tsx
  src/pages/posts/[slug].tsx
Labels: manual work :muscle:, refactoring :recycle:

#167 ✨ Added a nicer 404 page
  src/pages/404.tsx
Labels: user interface :lipstick:

#168 Improved footer styling
  src/components/footer.tsx
Labels: refactoring :recycle:

#169 Fixed darkmode icon
  src/lib/api/bedpres.ts
  src/pages/bedpres/[slug].tsx
Labels: bug :bug:
