Repository echo-webkom/echo-web-frontend, pull requests merged in 2022-04, with the labels that each got.

#1005 🔧 Change to public dataset and CDN
  .env.example
  .github/workflows/cypress_test.yaml
  Dockerfile
  README.md
  docker-compose.yaml
  src/lib/api/api.ts
Labels: architecture :classical_building:

#1010 👽 Add case that date can be null in backend response
  src/lib/api/decoders.ts
  src/lib/api/registration.ts
Labels: bug :bug:, architecture :classical_building:

#1032 💬 Fix heading grammar
  src/pages/valg/index.tsx
Labels: refactoring :recycle:

#1037 ✨ NextAuth Feide
  .env.example
  package.json
  src/pages/_app.tsx
  src/pages/api/auth/[...nextauth].ts
  src/pages/api/user.ts
  yarn.lock
Labels: feature :sparkles:

#1038 ⬇️ Downgrade @types/react
  package.json
  yarn.lock
Labels: dependencies :handshake:

#1052 🐛 Fix backend interop with profile page
  src/components/form-question.tsx
  src/components/form-term.tsx
  src/components/profile-info.tsx
  src/components/registration-form.tsx
  src/lib/api/decoders.ts
  src/lib/api/index.ts
  src/lib/api/types.ts
  src/lib/api/user.ts
  src/pages/api/user/index.ts
  src/pages/profile.tsx
Labels: bug :bug:

#1058 🔧 Set session maxAge to match Feide expire date
  src/pages/api/auth/[...nextauth].ts
Labels: bug :bug:

#1061 🔧 Disable next-pwa in dev mode
  next.config.js
Labels: architecture :classical_building:

#1063 Shortened event dates at index
  src/components/happening-key-info.tsx
Labels: user interface :lipstick:
