Repository echo-webkom/echo-web-frontend, pull requests merged in 2022-01, with the labels that each got.

#816 ✨ Add admin page for viewing registrations
  next-env.d.ts
  src/components/button-link.tsx
  src/lib/api/errors.ts
  src/lib/api/index.ts
  src/lib/api/registration.ts
  src/pages/registration/[slug].tsx
Labels: feature :sparkles:

#827 ♻️ Remove 'defaultProps' as it will be deprecated
  src/components/entry-box.tsx
  src/components/entry-list.tsx
  src/components/nav-link.tsx
  src/components/seo.tsx
Labels: refactoring :recycle:

#832 🚀 Move from Docker Hub to GHCR
  .github/workflows/cypress_test.yaml
  docker-compose.ci.yaml
Labels: devops :rocket:, architecture :classical_building:

#833 ♻️ Build & push only frontend image
  .github/workflows/cypress_test.yaml
  docker-compose.ci.yaml
Labels: bug :bug:, devops :rocket:

#837 🐛 Fix error when registrations array is empty
  src/pages/registration/[slug].tsx
Labels: bug :bug:

#838 ⬇️ Downgrade @chakra-ui/react to 1.7.3
  package.json
  yarn.lock
Labels: dependencies :handshake:

#856 🚀 Simplify compose files and use registry images
  .github/workflows/cypress_test.yaml
  docker-compose.ci.yaml
  docker-compose.yaml
Labels: devops :rocket:, refactoring :recycle:

#858 🚑 Fixed page refresh
  src/pages/bedpres/[slug].tsx
Labels: bug :bug:

#859 Symmetrical front page sections
  src/components/button-link.tsx
  src/components/entry-box.tsx
  src/components/entry-list.tsx
  src/components/hsp.tsx
  src/components/post-preview.tsx
  src/pages/index.tsx
Labels: user interface :lipstick:, refactoring :recycle:
