Repository echo-webkom/echo-web-frontend, pull requests merged in 2022-03, with the labels that each got.

#945 very important integral change in header logo
  src/components/header-logo.tsx
Labels: user interface :lipstick:

#958 🚑 Sort registrations by waitlist
  src/pages/registration/[slug].tsx
Labels: bug :bug:, user interface :lipstick:

#969 🔒 Make form registration the only way
  src/components/registration-form.tsx
  src/lib/api/decoders.ts
  src/lib/api/happening.ts
  src/lib/api/index.ts
  src/lib/api/registration.ts
  src/lib/api/types.ts
  src/pages/event/[slug].tsx
Labels: feature :sparkles:

#974 🐛 Fix empty reduce error
  src/components/happening-meta-info.tsx
Labels: bug :bug:

#975 🏷️ Fix HappeningInfo type
  src/lib/api/decoders.ts
  src/pages/event/[slug].tsx
Labels: bug :bug:

#981 💄 Increase number of bedpres/events on front page
  src/pages/index.tsx
Labels: user interface :lipstick:

#984 💄 Fix showing same degree year twice
  src/components/__tests__/happening-meta-info.test.tsx
  src/components/happening-meta-info.tsx
Labels: bug :bug:, user interface :lipstick:

#985 🐛 Fix serialize error
  src/lib/api/decoders.ts
  src/pages/event/[slug].tsx
Labels: bug :bug:
