Repository echo-webkom/echo-web-frontend, pull requests merged in 2022-02, with the labels that each got.

#870 hotfix/entry overview direction
  src/components/entry-overview.tsx
Labels: bug :bug:

#877 🐛 Fix sub routes not working on non-static pages
  src/components/info-panels.tsx
  src/pages/for-studenter/index.tsx
Labels: bug :bug:

#886 ♻️ Move identical pages to own component
  src/components/happening-page.tsx
  src/pages/bedpres/[slug].tsx
  src/pages/event/[slug].tsx
Labels: refactoring :recycle:

#889 ✅ Remove yarn test on commit
  .husky/pre-commit
Labels: testing :test_tube:

#890 Gjorde innlegg finere
  src/pages/posts/[slug].tsx
Labels: user interface :lipstick:

#896 ♿️ Fix accessibility issues from Lighthouse
  src/components/__tests__/navbar.test.tsx
  src/components/bedpres-preview.tsx
  src/components/color-mode-button.tsx
  src/components/footer.tsx
  src/components/student-group-section.tsx
Labels: user interface :lipstick:, refactoring :recycle:

#918 ⚡️ Change from `Avatar` in `bedpres-preview`
  src/components/bedpres-preview.tsx
Labels: bug :bug:, user interface :lipstick:

#924 💬 Change email in README
  README.md
Labels: documentation :memo:

#931 💄 Add Vercel banner in footer and README
  README.md
  public/powered-by-vercel.svg
  src/components/footer.tsx
Labels: user interface :lipstick:
